name: Update Star History

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          user: yongxin-ms
          template: repository
          repo: DisableSogouNetwork
          filename: metrics.svg
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
